apiVersion: apps/v1
kind: Deployment
metadata:
  name: geodanmaps-orggeodb-cluster-pgpool2
  labels:
    service: pgpool2
    environment: dev
    organisationCode: GEOD4222TEST    
spec:
  revisionHistoryLimit: 10  # removes old replicasets for deployment rollbacks
  strategy:
    rollingUpdate:
      maxUnavailable: 0  # Avoid Terminating and ContainerCreating at the same time
  selector:
    matchLabels:
      service: pgpool2
      environment: dev
      organisationCode: GEOD4222TEST 
  replicas: 2      
  template:
    metadata:
      labels:
        app: pgpool2
        service: pgpool2
        environment: dev
        organisationCode: GEOD4222TEST 
    spec:
      containers:
        - name: geodanmaps-orggeodb-cluster-pgpool2
          image: bitnami/pgpool:4-centos-7
          ports:
            - containerPort: 5432
          env:
            - name: "PGPOOL_ADMIN_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: orggeodbadmin.geodanmaps-orggeodb-cluster.credentials
                  key: username
            - name: "PGPOOL_ADMIN_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: orggeodbadmin.geodanmaps-orggeodb-cluster.credentials
                  key: password             
            - name: "PGPOOL_POSTGRES_USERNAME"
              valueFrom:
                secretKeyRef:
                  name: postgres.geodanmaps-orggeodb-cluster.credentials
                  key: username
            - name: "PGPOOL_POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres.geodanmaps-orggeodb-cluster.credentials
                  key: password
            - name: "PGPOOL_SR_CHECK_USER"
              valueFrom:
                secretKeyRef:
                  name: postgres.geodanmaps-orggeodb-cluster.credentials
                  key: username
            - name: "PGPOOL_SR_CHECK_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgres.geodanmaps-orggeodb-cluster.credentials
                  key: password
            - name: "PGPOOL_BACKEND_NODES"
              value: "0:geodanmaps-orggeodb-cluster:5432,1:geodanmaps-orggeodb-cluster-repl:5432"
---
apiVersion: v1
kind: Service
metadata:
  name: geodanmaps-orggeodb-cluster-pgpool2
spec:
  selector:
    service: pgpool2
    organisationCode: GEOD4222TEST
    environment: dev    
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
